Panther docker
husarion/panther-docker pull request #1
Opened 2022-09-21 14:54 UTC by KmakD

Initial draft for repo

2022-09-22 14:28 UTC, Kotochleb requested changes

2022-09-22 14:28 UTC, Kotochleb commented on .gitignore
> +__pycache__/
Can be replaced with [.gitignore](https://github.com/atlassian/docker/blob/master/.gitignore)

2022-09-22 14:28 UTC, Kotochleb commented on Dockerfile
> +    && rm -rf /var/lib/apt/lists/*
This step has to be right after third step

2022-09-22 14:28 UTC, Kotochleb commented on Dockerfile
> +    rosdep update --rosdistro $ROS_DISTRO && \
rosdep automatically runs `apt update` so
``` bash
apt clean
rm -rf /var/lib/apt/lists/* 
```
is needed afterwards.

2022-09-22 14:28 UTC, Kotochleb commented on compose.yaml
> +    ipc: host
This line is not needed

2022-09-22 14:28 UTC, Kotochleb commented on compose.yaml
> +    ipc: host
This line is not needed

2022-09-22 14:28 UTC, Kotochleb commented on compose.yaml
> +      context: .
It might use prebuilt docker

2022-09-22 14:28 UTC, Kotochleb commented on compose.yaml
> +    ipc: host
This line is not needed

2022-09-23 10:06 UTC, KmakD commented on Dockerfile
> +    && rm -rf /var/lib/apt/lists/*
:+1:

2022-09-23 10:06 UTC, KmakD commented on Dockerfile
> +    rosdep update --rosdistro $ROS_DISTRO && \
:+1:

2022-09-23 10:06 UTC, KmakD commented on compose.yaml
> +    ipc: host
:+1:

2022-09-23 10:06 UTC, KmakD commented on .gitignore
> +__pycache__/
:+1:

2022-09-26 10:51 UTC, Kotochleb requested changes

2022-09-26 10:51 UTC, Kotochleb commented on Dockerfile
> +CMD ["bash"]
This line can be removed

2022-09-26 11:02 UTC, Kotochleb approved these changes

2022-09-26 11:02 UTC, merged