Create compose.rviz.yaml
husarion/panther-docker pull request #24
Opened 2023-05-17 12:26 UTC by pkowalsk1

2023-05-18 14:35 UTC, KmakD requested changes

2023-05-18 14:35 UTC, KmakD commented on demo/panther.rviz
> +    Fixed Frame: base_link
I think fixed frame should be `odom`

2023-05-18 14:35 UTC, KmakD commented on demo/panther.rviz
> +      Value: true
Since panels are already being shown visually, do we really need to add image animations? Also, they both subscribe to the same topic.

2023-05-22 10:31 UTC, pkowalsk1 commented on demo/panther.rviz
> +      Value: true
But it looks awesome! It's kinda crazy...

2023-05-22 10:33 UTC, KmakD commented on demo/panther.rviz
> +      Value: true
Ok, but still topic names are the same

2023-05-22 10:45 UTC, KmakD approved these changes

2023-05-30 09:24 UTC, merged