Ros2 update
husarion/panther-docker pull request #36
Opened 2024-03-05 11:19 UTC by rafal-gorecki

### Description

- add Docker with ros2 image for physical Panther and simulation
- decrease number of compose configurations
- optimized building time 25% and image size 10%
- changes in readme

2024-03-08 08:43 UTC, KmakD requested changes

2024-03-08 08:43 UTC, KmakD commented on demo/panther.rviz
please remove odometry, may be confusing for end user

2024-03-08 10:51 UTC, rafal-gorecki commented on Dockerfile.hardware
> +RUN sed -i "/# <additional-user-commands>/i set -e -a && source /run/husarion/panther_config.env" /*_entrypoint.sh
Because is specified in `husarnet/ros`, I almost every repo `-docker` it is done like this, so the reason is standarisation.

2024-03-08 10:57 UTC, rafal-gorecki commented on README.md
> -## Running Simulation
I'd belive we want to user have easy acces to the leatest stable wersion. Thats why we have tag `husarion\panther-$ROS-DISTRO` which point to the latest stable version, if version is not stable, the image always contains varsion and date after $ROS_DISTRO.
Thank's to this the only command which user must execute is `docker compose pull`

2024-03-08 11:00 UTC, rafal-gorecki commented on .pre-commit-config.yaml
> +                                       # black checks it
Don't think so, removed

2024-03-08 11:03 UTC, rafal-gorecki commented on .pre-commit-config.yaml
> +  - repo: https://github.com/pre-commit/mirrors-clang-format
Don't think so, removed

2024-03-08 11:05 UTC, rafal-gorecki commented on Dockerfile.hardware
> +    colcon build --cmake-args "-DCMAKE_BUILD_TYPE=$BUILD_TYPE" "-DBUILD_TESTING=OFF" && \
Simlink added. Test can be addad, the only question which I have, do we need it because it caused 10 min longer build.

2024-03-08 11:07 UTC, rafal-gorecki commented on demo/compose.rviz.yaml
> +    image: husarion/rviz2:humble
I'd believe it is not needed.

2024-03-08 11:09 UTC, rafal-gorecki commented on demo/compose.rviz.yaml
> +    - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp # Default FastDDS do not work
From what I understand, the concept in Docker repositories is to keep minimal setups there. In the future, such things can be added in future demos, e.g. panther-autonomy

2024-03-08 11:23 UTC, rafal-gorecki commented on Dockerfile.simulation
> +    rm -rf src/panther_ros/panther_hardware_interfaces && \
I'd like to, but this is needed to build [panther_controller](https://github.com/husarion/panther_ros/blob/ros2-devel/panther_controller/package.xml)

2024-03-08 11:24 UTC, rafal-gorecki commented on Dockerfile.simulation
> +    rm -rf src/panther_ros/panther_hardware_interfaces && \
I have nice idea to fix this, but currently no time for this.

2024-03-08 11:26 UTC, rafal-gorecki commented on demo/compose.yaml
I don't understand

2024-03-08 11:26 UTC, rafal-gorecki commented on demo/compose.yaml
> -    - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
Not necessary

2024-03-08 11:30 UTC, rafal-gorecki commented on demo/compose.yaml
> +    #   dockerfile: Dockerfile.hardware
No, leaved for quick local test. I treat this repo dedicated to dev's more than customer. For customers we will create other demos.

2024-03-08 11:34 UTC, rafal-gorecki commented on demo/compose.yaml
> -    container_name: panther_ros
I don't see any added value

2024-03-11 11:43 UTC, KmakD commented on Dockerfile.simulation
> +    rm -rf src/panther_ros/panther_hardware_interfaces && \
How about sth like this in package.xml:
```
<depend condition="$HUSARION_ROS_BUILD_TYPE == hardware">panther_hardware_interfaces</depend>
```
It worked in ros 1

2024-03-11 11:47 UTC, KmakD commented on demo/compose.yaml
When the custom Rpi image for Panther is built it automatically copies (downloads from git repo) default `compose.yaml` file. And by default it looks for file  named `compose.minimal-setup.yaml`. Look here: https://github.com/husarion/panther-rpi-os-img/blob/2221a7ac14ff6f7cd75b49647d64991286b36e49/ansible/roles/ros/tasks/main.yaml#L88

2024-03-11 11:50 UTC, KmakD commented on demo/compose.yaml
> -    - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
I don't agree. By default it will be assigned to 0, but if someone wants to change it then just change `ROS_DOMAIN_ID` env variable instead of modifying the compose file.

2024-03-11 12:01 UTC, KmakD commented on demo/compose.yaml
> +    #   dockerfile: Dockerfile.hardware
This compose will be a default compose file copied to Panther image, so it should not contain comments. This should be removed.

2024-03-11 12:05 UTC, KmakD commented on demo/compose.yaml
> -    container_name: panther_ros
It's easier to navigate and debug containers when you have static names. Useful for support and personally when you get used to them it helps during development. Also, keeps compatibility with ROS 1 where they were used, and they may be reference in few places in current documentation

2024-03-11 12:20 UTC, KmakD commented on README.md
> -## Running Simulation
Two things:
- compose.yaml file will be available on Panthers Rpi, no point in cloning repo there - just modify tag
- for all ours docker images marked as stable tags should have dates, and this is true for all robots. There is no universal tag that points to stable version. So to use new stable version it is necessary to modify compose file

2024-03-11 12:26 UTC, KmakD commented on Dockerfile.hardware
> +RUN sed -i "/# <additional-user-commands>/i set -e -a && source /run/husarion/panther_config.env" /*_entrypoint.sh
Ok, haven't noticed this change

2024-03-11 12:33 UTC, KmakD commented on Dockerfile.hardware
> +    colcon build --cmake-args "-DCMAKE_BUILD_TYPE=$BUILD_TYPE" "-DBUILD_TESTING=OFF" && \
That depends on how and where we would like to run the tests. Thing to discuss I gess

2024-03-11 12:38 UTC, KmakD reviewed
I screw a bit but adding comments directly, not in review, so this dummy comment :sweat_smile:

2024-03-18 08:30 UTC, rafal-gorecki commented on Dockerfile.simulation
> +    rm -rf src/panther_ros/panther_hardware_interfaces && \
That's exactly what I was thinking. I will add it soon.

2024-03-18 10:08 UTC, rafal-gorecki commented on Dockerfile.hardware
> +    colcon build --cmake-args "-DCMAKE_BUILD_TYPE=$BUILD_TYPE" "-DBUILD_TESTING=OFF" && \
I add `ARG BUILD_TEST=OFF`, so we can change behaiour in github actions (e.g. in case if we want to build test only for stable version).

2024-03-18 10:15 UTC, rafal-gorecki commented on README.md
> -## Running Simulation
It is universal tag `humble`

2024-03-18 14:17 UTC, KmakD requested changes

2024-03-18 14:17 UTC, KmakD commented on demo/compose.rviz.yaml
> +    container_name: panther_ros
```suggestion
    container_name: rviz2
```

2024-03-18 14:17 UTC, KmakD commented on README.md
> +> If you have an NVIDIA GPU, it is worth changing the compos configuration from cpu-config to gpu-config. For this purpose, it is necessary to install [NVIDIA Container Toolkit](https://docs.nvidia.c
```suggestion
> If you have an NVIDIA GPU, it is worth changing the compose configuration from cpu-config to gpu-config. For this purpose, it is necessary to install [NVIDIA Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html). With NVIDIA Container Toolkit installed, modify following Docker compose file by replacing `*cpu-config` with `*gpu-config`: [compose.simulation.yaml](./demo/compose.simulation.yaml).
```
Just to be more specyfic

2024-03-18 14:20 UTC, KmakD approved these changes

2024-03-18 14:37 UTC, merged